name: SBOM

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Generate project SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate SBOM
        uses: ./
        with:
          path: '.'
          format: 'cyclonedx-json'
          output-file: 'mikebom-action.sbom.cdx.json'
          artifact-name: 'project-sbom'

